import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { build, transform } from "esbuild";

const root = process.cwd();
const publicDir = join(root, "public");
const outputPath = join(publicDir, "build", "app.compiled.js");
const desktopBridgeOutputPath = join(publicDir, "build", "desktop.bridge.js");

const jsxSources = [
  "components-common.jsx",
  "feedback-client.js",
  "feedback-widget.jsx",
  "audio-actions.jsx",
  "tweaks-panel.jsx",
  "screen-library.jsx",
  "screen-desk.jsx",
  "screen-letter.jsx",
  "screen-workspace.jsx",
  "screen-review.jsx",
  "screen-revision.jsx",
  "screen-outputs.jsx",
  "screen-weave.jsx",
  "media-components.jsx",
  "screen-studio.jsx",
  "screen-gather.jsx",
  "screen-references.jsx",
  "screen-book.jsx",
  "setup-helper.jsx",
  "app.jsx",
];

const compiled: string[] = [
  "/* Generated by scripts/build-static-browser-shell.ts. Do not edit by hand. */",
  "/* eslint-disable */",
];

const feedbackApiBase =
  process.env.VITE_PILLAR_PRESS_FEEDBACK_API_BASE ||
  process.env.VITE_PILLAR_FEEDBACK_API_BASE ||
  process.env.VITE_PRISM_FEEDBACK_API_BASE ||
  "";

compiled.push(
  `window.PILLAR_PRESS_FEEDBACK_API_BASE = ${JSON.stringify(feedbackApiBase)};`
);

for (const source of jsxSources) {
  const sourcePath = join(publicDir, source);
  const code = await readFile(sourcePath, "utf8");
  const result = await transform(code, {
    loader: "jsx",
    jsxFactory: "React.createElement",
    jsxFragment: "React.Fragment",
    target: "es2015",
    legalComments: "none",
    sourcefile: source,
  });
  compiled.push(`\n/* ${source} */\n${result.code}`);
}

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, `${compiled.join("\n")}\n`);
await build({
  entryPoints: [join(publicDir, "desktop-bridge.js")],
  outfile: desktopBridgeOutputPath,
  bundle: true,
  format: "iife",
  platform: "browser",
  target: "es2018",
  legalComments: "none",
  logLevel: "silent",
});

console.log(`Compiled ${jsxSources.length} JSX browser modules to ${outputPath}`);
console.log(`Bundled desktop bridge to ${desktopBridgeOutputPath}`);
